<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'prestashop.module.demoextendsymfonyform.uploader.supplier_extra_image_uploader' shared service.

return $this->services['prestashop.module.demoextendsymfonyform.uploader.supplier_extra_image_uploader'] = new \PrestaShop\Module\DemoExtendSymfonyForm\Uploader\SupplierExtraImageUploader(${($_ = isset($this->services['prestashop.module.demoextendsymfonyform.repository.supplier_extra_image_repository']) ? $this->services['prestashop.module.demoextendsymfonyform.repository.supplier_extra_image_repository'] : $this->load('getPrestashop_Module_Demoextendsymfonyform_Repository_SupplierExtraImageRepositoryService.php')) && false ?: '_'});
