<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.module.cellule.grid.factory' shared service.

return $this->services['prestashop.module.cellule.grid.factory'] = new \PrestaShop\PrestaShop\Core\Grid\GridFactory(${($_ = isset($this->services['prestashop.module.cellule.repository.cellule_definition_factory']) ? $this->services['prestashop.module.cellule.repository.cellule_definition_factory'] : $this->load('getPrestashop_Module_Cellule_Repository_CelluleDefinitionFactoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.module.cellule.grid.data_factory']) ? $this->services['prestashop.module.cellule.grid.data_factory'] : $this->load('getPrestashop_Module_Cellule_Grid_DataFactoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.core.grid.filter.form_factory']) ? $this->services['prestashop.core.grid.filter.form_factory'] : $this->load('getPrestashop_Core_Grid_Filter_FormFactoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.core.hook.dispatcher']) ? $this->services['prestashop.core.hook.dispatcher'] : $this->getPrestashop_Core_Hook_DispatcherService()) && false ?: '_'});
