<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.module.demoextendsymfonyform.repository.supplier_extra_image_repository' shared service.

return $this->services['prestashop.module.demoextendsymfonyform.repository.supplier_extra_image_repository'] = ${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'}->getRepository('PrestaShop\\Module\\DemoExtendSymfonyForm\\Entity\\SupplierExtraImage');
