admin_cellule:
  path: /cellule
  methods: [GET]
  defaults:
    _controller: 'Cellule\Controller\Admin\AdminCelluleController::listAction'
    _legacy_controller: AdminCellule

admin_cellule_view:
   path: /cellule/view/{celluleId}
   defaults:
       _controller: 'Cellule\Controller\Admin\AdminCelluleController::viewAction'
       _legacy_controller: AdminCellule
   methods: [GET]
    
admin_cellule_delete:
  path: /cellule/delete/{celluleId}
  defaults:
    _controller: 'Cellule\Controller\Admin\AdminCelluleController::deleteAction'
    _legacy_controller: AdminCellule
  methods: [GET]
     

admin_cellule_toggle:
  path: /admin/cellule/toggle/{celluleId}/{valid}
  defaults:
    _controller: 'Cellule\Controller\Admin\AdminCelluleController::validateAction'
  methods: [GET, POST]




