services:
  _defaults:
    public: true

  prestashop.module.cellule.repository:
    class: Cellule\Repository\CelluleRepository
    arguments:
      $connection: '@doctrine.dbal.default_connection'
      $dbPrefix: '%database_prefix%'
      $languages: '@=service("prestashop.adapter.legacy.context").getLanguages(false, service("prestashop.adapter.shop.context").getContextShopID())'
      $translator: '@translator'

  prestashop.module.cellule.repository.cellule_definition_factory:
    class: 'Cellule\Core\Grid\Definition\Factory\CelluleDefinitionFactory'
    parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
    public: true

# Register ProductQueryBuilder
  prestashop.module.cellule.grid.query_builder:
    class: Cellule\Core\Grid\Query\CelluleQueryBuilder
    parent: 'prestashop.core.grid.abstract_query_builder'
    arguments:
        - "@=service('prestashop.adapter.legacy.context').getContext().language.id"
    public: true

  # Grid Data Factory
  prestashop.module.cellule.grid.data_factory:
    class: '%prestashop.core.grid.data.factory.doctrine_grid_data_factory%'
    arguments:
      $gridQueryBuilder: '@prestashop.module.cellule.grid.query_builder'
      $hookDispatcher: '@prestashop.core.hook.dispatcher'
      $queryParser: '@prestashop.core.grid.query.doctrine_query_parser'
      $gridId: 'cellule'

  prestashop.module.cellule.grid.factory:
    public: true
    class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
    arguments:
      - '@prestashop.module.cellule.repository.cellule_definition_factory'
      - '@prestashop.module.cellule.grid.data_factory'
      - '@prestashop.core.grid.filter.form_factory'
      - '@prestashop.core.hook.dispatcher'