<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAknjycd\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAknjycd/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerAknjycd.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerAknjycd\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerAknjycd\appProdProjectContainer([
    'container.build_hash' => 'Aknjycd',
    'container.build_id' => '02e2aa0c',
    'container.build_time' => 1686387919,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAknjycd');
