<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2htbzlj\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2htbzlj/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container2htbzlj.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container2htbzlj\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container2htbzlj\appDevDebugProjectContainer([
    'container.build_hash' => '2htbzlj',
    'container.build_id' => '8e05d88c',
    'container.build_time' => 1686472397,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2htbzlj');
