<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQxezxub\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQxezxub/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQxezxub.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQxezxub\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerQxezxub\appDevDebugProjectContainer([
    'container.build_hash' => 'Qxezxub',
    'container.build_id' => '11046bc4',
    'container.build_time' => 1684067960,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQxezxub');
